apiVersion: apps/v1
kind: Deployment
metadata:
  name: discordlm-deployment
  labels:
    app: discordlm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discordlm
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: discordlm
      annotations:
        discordlm.com/restartedAt: "1750888362"
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: discordlm
        image: ghcr.io/aronson/discordlm:{{IMAGE_TAG}}
        imagePullPolicy: Always
        ports:
        - containerPort: 3334
        envFrom:
        - configMapRef:
            name: discordlm-config
        - secretRef:
            name: discordlm-secrets
        volumeMounts:
        - name: characters-storage
          mountPath: /app/characters
        - name: logs-storage
          mountPath: /app/logs
      volumes:
      - name: characters-storage
        persistentVolumeClaim:
          claimName: discordlm-pvc
      - name: logs-storage
        persistentVolumeClaim:
          claimName: discordlm-logs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: discordlm-service
spec:
  type: NodePort
  selector:
    app: discordlm
  ports:
    - protocol: TCP
      port: 3334
      targetPort: 3334