apiVersion: apps/v1
kind: Deployment
metadata:
  name: discordlm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discordlm
  template:
    metadata:
      labels:
        app: discordlm
    spec:
      containers:
      - name: discordlm
        image: ghcr.io/glompai/discordlm:${IMAGE_TAG}
        ports:
        - containerPort: 8080
        - containerPort: 8081
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        envFrom:
        - secretRef:
            name: discordlm-secrets
        - configMapRef:
            name: discordlm-config
        volumeMounts:
        - name: characters
          mountPath: /app/characters
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: characters
        hostPath:
          path: /root/discordlm/characters
      - name: logs
        hostPath:
          path: /root/discordlm/logs