apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${DEPLOYMENT_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${DEPLOYMENT_NAME}
  template:
    metadata:
      labels:
        app: ${DEPLOYMENT_NAME}
    spec:
      containers:
      - name: discordlm
        image: ghcr.io/glompai/discordlm:${IMAGE_TAG}
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /readyz
            port: 18888
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 18888
          initialDelaySeconds: 15
          periodSeconds: 20
        envFrom:
        - secretRef:
            name: ${SECRET_NAME}
        - configMapRef:
            name: ${CONFIG_MAP_NAME}
        env:
        - name: PREMIUM_GUILD_ID
          value: "1304097485136072714"
        env:
        - name: CLOUDFLARE_TUNNEL_ID
          value: "1630c589-6e93-4082-a703-860e44aa831c"
        - name: CLOUDFLARE_CREDENTIALS_FILE
          value: "/root/.cloudflared/1630c589-6e93-4082-a703-860e44aa831c.json"
        - name: CLOUDFLARE_HOSTNAME
          value: "avatar.glomp.ai"
        volumeMounts:
        - name: characters
          mountPath: /app/characters
        - name: logs
          mountPath: /app/logs
        - name: cloudflare-credentials
          mountPath: /root/.cloudflared
      volumes:
      - name: characters
        hostPath:
          path: ${CHARACTER_PATH}
      - name: logs
        hostPath:
          path: /root/discordlm/logs
      - name: cloudflare-credentials
        secret:
          secretName: cloudflare-credentials