apiVersion: v1
kind: ConfigMap
metadata:
  name: discordlm-config
data:
  LLM_PROVIDER: "gemini"
  MODEL_NAME: "models/gemini-1.5-flash"
  OPENAI_BASE_URL: "https://be.pingas.org/v1"
  OPENAI_VISION_SUPPORT: "false"
  TOKEN_LIMIT: "32000"
  ENABLE_AVATAR_SERVER: "true"
  AVATAR_PORT: "3334"
  PUBLIC_AVATAR_BASE_URL: "https://cutie.pingas.org"
  MAX_HISTORY_MESSAGES: "300"
  RATE_LIMIT_PER_MINUTE: "4"
  DEBUG: "true"
  INFERENCE_PARALLELISM: "10"