apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-credentials
type: Opaque
stringData:
    1630c589-6e93-4082-a703-860e44aa831c.json: |
        {"AccountTag":"f5f06a9ba2741789f80c61c2f7135228","TunnelSecret":"REDACTED_CLOUDFLARE_TUNNEL_SECRET=","TunnelID":"1630c589-6e93-4082-a703-860e44aa831c","Endpoint":""}
